version: '3'
services:

  # frontend web server
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./:/code

  # database server
  db:
    image: "postgres:latest"

